In [21]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.datasets import load_digits

In [22]:
digits = load_digits()

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [24]:
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9648148148148148

In [25]:
lr.get_params()

{'C': 1.0,
 'class_weight': None,
 'dual': False,
 'fit_intercept': True,
 'intercept_scaling': 1,
 'l1_ratio': None,
 'max_iter': 1000,
 'multi_class': 'deprecated',
 'n_jobs': None,
 'penalty': 'l2',
 'random_state': None,
 'solver': 'lbfgs',
 'tol': 0.0001,
 'verbose': 0,
 'warm_start': False}

In [26]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9777777777777777

In [27]:
sv = SVC()
sv.fit(X_train, y_train)
sv.score(X_test, y_test)

0.9944444444444445

In [28]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [52]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
  print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [30]:
def get_score(model, X_train, X_test, y_train, y_test):
  model.fit(X_train, y_train)
  return model.score(X_test, y_test)

In [31]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [32]:
scores_lr = []
scores_sv = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
  X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                      digits.target[train_index], digits.target[test_index]
  scores_lr.append(get_score(LogisticRegression(max_iter=1000), X_train, X_test, y_train, y_test))
  scores_sv.append(get_score(SVC(max_iter=1000), X_train, X_test, y_train, y_test))
  scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [33]:
scores_lr

[0.9248747913188647, 0.9432387312186978, 0.9148580968280468]

In [34]:
scores_sv

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [35]:
scores_rf

[0.9398998330550918, 0.9449081803005008, 0.9198664440734557]

In [36]:
from sklearn.model_selection import cross_val_score

In [43]:
cross_val_score(LogisticRegression(max_iter=400), digits.data, digits.target)

array([0.92222222, 0.87222222, 0.94150418, 0.94150418, 0.89693593])

In [44]:
cross_val_score(SVC(max_iter=400), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [50]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target)

array([0.92222222, 0.90277778, 0.94986072, 0.94986072, 0.92479109])